project:
  type: website
  title: "Learn with Jen"
  output-dir: _site

website:
  navbar:
    title: "Learn with Jen"
    left:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html
