---
title: "De-identified Autobiographies: The Challenges of Disseminating Personal Research"
author: "Jennifer Mosley"
format: html
editor: visual
---

When I mention to new acquaintances that I study self-concept, I am met with some looks of perplexity. Understandably, the self is a broad topic in psychology: all roads in social psychology lead to the self in some way. Additionally, the prevalence and empirical feasibility of the self has waded ebbs-and-flows throughout its scholarly history; the self, as a line of research, requires great attention to individual differences and interdisciplinary considerations that most methods may not adequately address.

Despite this, the continuous evolution of computational methods have provided self-concept research with newfound possibilities for robust, interpretable findings. Also, like most intellectual newground, thinking outside the psychological box has positioned this line of research toward great innovation and meaningful applications surpassing psychology.

\[GIF\]

So, what do I really do? In short, my work aims to model self, as a working concept, through autobiographical memories and the subjective relationships between memories that altogether embody a coherent sense of self and identity. I analyze and visualize directed connections between memories using network analysis, so the iGraph package in R has been critical for this research.

In fact, in my department, most use R for statistical methods such as regression and mediation analyses. Anything that is inherently multivariate, like network analysis, may become a task for MATLAB or Python, especially for neuroimaging analysis. I think it would surprise some of my peers that these seemingly-rigorous analyses are carried out with the same software they use everyday for data wrangling, analysis, and visualization. Luckily for me, these R packages minimizes the learning curve and maximizes efficiency when implementing network analysis and visualization.

\[GIF\]

Despite how welcoming R has been for me as I navigate this methodology, I am still exploring how to optimize my R skillset and workflow to best communicate exciting findings about these network models while also maintaining a high standard for participant privacy. I have encountered many unique challenges in presenting my research from self-concept land, and individual differences and privacy have been the most challenging when discussing my work with others. My network examples for talks are usually created from my own experiences, or generated randomly by my analysis software. While this has worked just fine for demo purposes, I would someday like to show real data and real memory networks to my audience; my memory networks are humanly-biased, and automated networks are not human-representative.

\[GIF\]

For these reasons, I tend to be very selective with the participant data that I share and even analyze. My behavioral analysis scripts can also invade participant privacy, as creating networks first requires memory data, the subjective connections between them, and subjective evaluations of each memory. Same goes for my neuroimaging data, where the raw brain images themselves are sensitive. Can you recognize a person by their skull? I can and I have from images alone. In my analysis, I often pair neuroimaging data with the behavioral network data, reintroducing original challenges of privacy.

As a researcher-in-training, I am learning new ways to communicate and disseminate my work through means that are intellectually meaningful but also mindful of my participants. Since the process of de-identifying autobiographies is challenging enough, I primarily use R for statistical analysis and visualizations in my research. More specifically, I am an avid user of iGraph and ggplot for visualizing study results and interpretations. Additionally, though needless to say, tidyverse has been a lifesaver for wrangling this large-scale, mixed-methods data. As I delve into a more qualitative world of autobiographical narratives (which will be particularly interesting in the de-identifying autobiographies department), I will apply semantic analysis to these narratives, likely using VADER to assess sentiment of transcribed autobiographies.

Moving forward in this work, given my existing skillset in R, I would like to learn how to best integrate neuroimaging data workflows through R, using software like FSL and FreeSurfer for processing and functional activity analysis. With this integration, my analysis workflow will be more streamlined and replicable for when I inevitably need to repeat the same workflow. I aim to learn how to use packages like brainwaver to employ functional connectivity analyses using R.

\[GIF\]

There are many challenges to this line of work, understanding how personal memories support the basis of who we are. Indeed, simple yet robust methods are needed to make this happen, which is why I look to stay within the world of R for data wrangling and statistical analysis. I have research assistants working on my research team who are particularly keen to gain knowledge in these data domains, though these research assistants do not learn about R until after their undergraduate studies. Through me, they have learned everything from the basics of R to applications of iGraph in contexts outside of the research we conduct. I intend to explore and study new methods for analyzing and visualizing autobiographical memory maps in a way that reflects the significance of the individual in this line of research.
